server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.200.130:8848 # nacos地址 如果是80则是negix代理
      discovery:
       namespace: 0f621710-382b-4747-b1f6-ef999dab159b #命名空间 命名空间id
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id 自定义，需要唯一
          uri: lb://userservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，判断请求是否符合路由规则
            # - Path=/user/**, /adress/** # 这个是按照路径匹配的，只要以/user/开头就符合要求 此处新增了一个/adress/开头的路径
            - Path=/userApi/**
          #default-filters: # 默认过滤器
          #- AddRequestHeader=name, zhangsan
          #- StripPrefix=1
          filters: # 过滤器
            #- AddRequestHeader=authorization, admin # 添加请求 过滤的条件
            - StripPrefix=1 # 过滤掉路由断言中的第一个路径
        - id: order
          uri: lb://orderservice
          predicates:
            - Path=/orderApi/**
          filters:
            - StripPrefix=1
      globalcors: #全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:809/0"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
